import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import PokeCard from '../components/pokecard'
import AshCard from '../components/AshCard'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.bg}>
        <AshCard/>
        <div className='space'>
        <PokeCard text='004 Charmander' src='Charmander.png'/>
        <PokeCard text='025 Charman' src='Charmander.png' me='30px'/>
        <PokeCard text='004 Charmander' src='Charmander.png'/>
        <PokeCard text='004 Charmander' src='Charmander.png'/>
        </div>
      </main>
    </>
  )
}
