import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import PokeCard from '../components/pokecard'
import AshCard from '../components/AshCard'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <AshCard></AshCard>
      <div className='Cardspace'> 
       <PokeCard text='025 Pikachu' src="Pikachu.png" margin="40px"/>
       <PokeCard text='001 Bulbasaur' src="Bulbasaur.png"/>
        <PokeCard text='004 Charmander' src="Charmander.png"/>
        <PokeCard text='034 Charmander' src="Charmander.png" src1='Pokeball.png'/>
        </div>
      </main>
    </>
  )
}
